
mysql:
  image: mariadb:10.0
  links:
    - replicas

replicas:
  build: .
  volumes:
    - $HOME/.ssh:/root/ssh:ro
    - $SSH_AUTH_SOCK:$SSH_AUTH_SOCK
  environment:
    LOCAL_PORT: 3306
    REMOTE_HOST: enwiki.analytics.db.svc.eqiad.wmflabs
    REMOTE_PORT: 3306
    TUNNEL_HOST: wiki-relicas-tunnel
    SSH_AUTH_SOCK: $SSH_AUTH_SOCK
